eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 9090

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter
        - id: book-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/books/**
          filters:
            - AuthenticationFilter
        - id: author-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/authors/**
